apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
#  type: LoadBalancer
  type: ClusterIP   # Deploying this as a Cluster IP so that this is accessible only inside Cluster and not accessible to outside world.
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysql